#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source ${OPENSHIFT_HOMEDIR}python-2.6/virtenv/bin/activate
 
export PYTHON_EGG_CACHE=${OPENSHIFT_HOME_DIR}python-2.6/virtenv/lib/python-2.6/site-packages

APP_ROOT=${OPENSHIFT_REPO_DIR}app
MANAGE="python ${APP_ROOT}/manage.py "

if [ ! -f $OPENSHIFT_DATA_DIR/production.db ]
then
  echo "COPYING DEV DB ++++++++++++++++++"
  cp ${APP_ROOT}/dev.db $OPENSHIFT_DATA_DIR/production.db
  echo "Executing $MANAGE make_admin"
  #$MANAGE make_admin
else
  $MANAGE syncdb --noinput
  $MANAGE migrate --noinput
fi

#$MANAGE createdb --noinput --nodata


echo "Executing $MANAGE collectstatic --noinput -v0'"
$MANAGE collectstatic --noinput -v0
